---
# Install collections locally using the following command:
# ansible-galaxy collection install -r collections/requirements.yml -f

collections:
  - name: ansible.netcommon
  - name: cisco.ios
  - name: awx.awx
